export const coverageCategories = [
  {
    id: "consultas",
    title: "Consulta generalista",
    description: "Consultas selecionadas inclusas; as demais recebem o desconto do plano.",
    procedures: [
      "Retorno Clínico",
      "Consulta Clínico Geral",
      "Retorno em Horário de Plantão",
      "Retorno Domiciliar",
      "Consulta Clínico Geral para Definição do Protocolo Vacinal",
      "Consulta Domiciliar",
      "Consulta Domiciliar para Definição de Protocolo Vacinal",
      "Consulta Plantão",
    ],
  },
  {
    id: "urgencia-emergencia",
    title: "Urgência e emergência",
    description: "Atendimento imediato incluído em todos os planos após a carência.",
    procedures: [
      "Consulta de urgência",
      "Consulta de emergência",
    ],
  },
  {
    id: "especialistas",
    title: "Consultas com especialistas",
    description: "Avaliação especializada com desconto conforme o plano escolhido.",
    procedures: [
      "Consulta com Cardiologista veterinário",
      "Consulta com Dermatologista veterinário",
      "Consulta com Ortopedista veterinário",
      "Consulta com Oftalmologista veterinário",
      "Consulta com Endocrinologista veterinário",
      "Consulta com especialista em Medicina Felina",
      "Consulta com Neurologista veterinário",
      "Consulta com Oncologista veterinário",
      "Consulta com Nefrologista veterinário",
      "Consulta com Nutrólogo veterinário",
    ],
  },
  {
    id: "vacinas",
    title: "Vacinas",
    description: "Imunização essencial para cães e gatos, conforme indicação veterinária.",
    procedures: [
      "Vacina da Gripe",
      "Vacina da Raiva",
      "Vacina Quíntupla (V5 ou V3/V4 + FeLV)",
      "Vacina Polivalente V7/V8",
      "Vacina Tríplice (V3) / Quádrupla (V4)",
      "Vacina Polivalente V10",
    ],
  },
  {
    id: "exames-simples",
    title: "Exames laboratoriais simples",
    description: "Análises de rotina para prevenção, diagnóstico e acompanhamento.",
    procedures: [
      "Hemograma",
      "Urinálise (E.Q.U.)",
      "Pesquisa de Ectoparasitas (Pele / Ouvido)",
      "Alanina Aminotransferase (TGP/ALT)",
      "Glicemia laboratório",
      "Creatinina",
      "Fosfatase Alcalina (FA)",
      "Fósforo",
      "Uréia",
      "Triglicerídeos",
      "Colesterol total",
      "Albumina",
      "Proteínas Totais",
      "Aspartato Aminotransferase (TGO/AST)",
      "Gama Glutamil Transferase (GGT)",
      "Cálcio total ou urinário",
      "Potássio",
      "Análise de cálculos urinários (qualitativo)",
      "Sódio",
      "Frutosamina",
      "Bilirrubinas - totais e frações",
      "Cálcio iônico",
      "Contagem de reticulócitos",
      "Pesquisa de hematozoários",
      "Glicemia fita",
      "Cloro",
      "Magnésio",
      "Pesquisa de sangue oculto nas fezes",
      "Ferro",
      "Tempo de Trombina (TT) e/ou Tempo de Tromboplastina Parcial Ativada (TTPA)",
      "Fibrinogênio",
      "Ácido úrico",
      "Amilase",
      "Amônia",
      "Beta Hidroxibutirato",
      "Eletroforese de Colesterol",
      "Lipase Sérica",
      "Hematócrito",
      "Pesquisa de Células de Lúpus Eritematoso",
      "Pesquisa de Corpúsculo de Lentz",
      "Velocidade de Hemossedimentação (VHS)",
      "Tempo de Protrombina (TP)",
      "Tempo de Coagulação",
      "Tempo de Sangramento",
      "Coproparasitológico Simples (1 amostra)",
      "Proteínas Totais e Frações",
      "Relação Proteína / Creatinina Urinária (RPC/RPU/CU)",
      "Ácidos Biliares (Pré e/ou Pós-prandial)",
      "Lactato laboratório",
      "CK - Creatinoquinase Total",
      "Hemoglobina Glicada",
      "Relação Cortisol - Creatinina Urinária",
      "Coproparasitológico Funcional",
      "Colesterol total e frações",
      "Eletroforese de Proteína Sérica",
      "Ferritina",
      "Mielograma",
      "Curva Glicêmica",
    ],
  },
  {
    id: "exames-complexos",
    title: "Exames laboratoriais complexos",
    description: "Investigações avançadas, culturas, sorologias e testes moleculares.",
    procedures: [
      "Micológico direto",
      "Análise Citológica Otológica",
      "Análise Citológica de Pele",
      "Análise Citológica Aspirativa (BAAF/CAAF)",
      "Cultura fúngica",
      "Tricograma",
      "Coloração de Gram",
      "Hemocultura com Antibiograma",
      "Cultura bacteriológica + Antibiograma",
      "Adenovírus Canino Tipo 2 - PCR (CAV-2)",
      "Babesiose - Sorologia IgM (Babesia spp.)",
      "Erliquiose - Sorologia IgM (Ehrlichia canis)",
      "Imunodeficiência Viral Felina (FIV) - Sorologia",
      "Leucemia Viral Felina (FeLV) - Sorologia",
      "Micoplasma Felino - Sorologia",
      "Parvovírus Canino - IgG",
      "Babesiose - Sorologia IgG (Babesia canis)",
      "Babesiose - Sorologia IgM (Babesia canis)",
      "Cinomose - IgG",
      "Cinomose - IgM",
      "Erliquiose - Sorologia IgG (Ehrlichia spp.)",
      "Erliquiose - Sorologia IgM (Ehrlichia spp.)",
      "Erliquiose - Sorologia IgG (Ehrlichia canis)",
      "Coronavírus Felino - Sorologia (Peritonite Infecciosa Felina)",
      "FIV + FeLV Sorologia",
      "Parvovírus Canino - IgM",
      "Parvovírus Felino - IgG",
      "Parvovírus Felino - IgM",
      "Dirofilariose - Sorologia",
      "Parvovírus canino - PCR",
      "Cinomose - PCR",
      "Imunodeficiência Viral Felina (FIV) - PCR",
      "Leucemia Viral Felina (FeLV) - PCR",
      "Leishmaniose - PCR",
      "Babesiose - PCR (Babesia canis)",
      "Giárdia - PCR",
      "Adenovírus Canino Tipo 1 - PCR (CAV-1)",
      "Anaplasmose - PCR (Anaplasma platys)",
      "Anaplasmose - Sorologia (Anaplasma platys)",
      "Babesiose - Sorologia IgG (Babesia spp.)",
      "Bordetella Bronchiseptica - PCR",
      "Coronavírus Entérico Canino - PCR",
      "Cryptococcus SP - PCR",
      "Erliquiose - PCR (Ehrlichia spp.)",
      "Erliquiose - PCR (Ehrlichia canis)",
      "Coronavírus Felino - PCR (Peritonite Infecciosa Felina)",
      "Herpes Vírus Canino - PCR",
      "Parvovírus Felino - PCR",
      "Herpes Vírus Felino - PCR",
      "Babesiose - PCR (Babesia sp.)",
      "Micoplasma Felino - PCR",
      "Cinomose - Teste Rápido",
      "FIV + FeLV PCR",
    ],
  },
  {
    id: "procedimentos-clinicos",
    title: "Procedimentos clínicos",
    description: "Cuidados ambulatoriais e intervenções realizadas pela equipe clínica.",
    procedures: [
      "Coleta de material para exames cobertos",
      "Coleta por cistocentese",
      "Aplicação de Injeção Subcutânea ou Intramuscular (SC/IM) - Com Medicação",
      "Curativo Simples",
      "Sutura de pele simples",
      "Drenagem de abscesso e/ou hematomas",
      "Fluidoterapia: Ringer Lactato (RL)/Soro Fisiológico/Glicofisiológica",
      "Desobstrução Uretral",
      "Aplicação de Injeção Intravenosa (IV) - Com Medicação",
      "Fluidoterapia: Coloide",
      "Fluidoterapia: Hipertônica/Manitol",
      "Reanimação",
      "Limpeza e Debridamento",
      "Retirada de Anzol",
      "Amputação de unha",
      "Lavagem Gástrica",
      "Carvão Ativado + Lavagem Gástrica",
      "Lavagem Vesical",
      "Inalação (15 Minutos)",
      "Sedação / tranquilização",
      "Retirada de bicheira, berne ou bicho-de-pé",
      "Oxigenoterapia (até 1 hora)",
      "Curativo complexo",
      "Ressecção de Verrugas ou Papilomas",
      "Lavagem Intestinal",
      "Imobilização de fraturas simples",
      "Remoção de Espinhos (Ouriços)",
    ],
  },
  {
    id: "imagem",
    title: "Exames de imagem",
    description: "Diagnóstico por imagem para apoiar decisões clínicas com agilidade.",
    procedures: [
      "Acompanhamento ultrassonográfico abdominal",
      "Raio-x (por imagem realizada)",
      "Contraste radiológico",
      "Raio-x Plantão (por posição / projeção)",
      "Ultrassonografia abdominal",
      "Ultrassonografia abdominal Plantão",
    ],
  },
  {
    id: "servicos",
    title: "Serviços",
    description: "Serviços complementares disponíveis na estrutura Cuidary.",
    procedures: [
      "Microchipagem",
      "Locação de sala para atendimento volante",
    ],
  },
  {
    id: "hospedagem-pet-sitter",
    title: "Hospedagem e Pet Sitter",
    description: "Consulte a disponibilidade e os benefícios para cuidados fora do hospital.",
    procedures: [
      "Hospedagem",
      "Pet Sitter",
    ],
  },
  {
    id: "estetica",
    title: "Estética e bem-estar",
    description: "Banho, tosa e cuidados estéticos com desconto conforme o plano escolhido.",
    procedures: [
      { name: "Banho avulso", detail: "Pequeno", price: 45 },
      { name: "Banho avulso", detail: "Médio • pelo curto", price: 55 },
      { name: "Banho avulso", detail: "Médio • pelo longo", price: 65 },
      { name: "Banho avulso", detail: "Grande • pelo curto", price: 80 },
      { name: "Banho avulso", detail: "Grande • pelo longo", price: 100 },
      { name: "Banho avulso", detail: "Gatos", price: 40 },
      {
        name: "Banho — pacote mensal",
        detail: "Pequeno • 4 banhos em até 1 mês • R$ 25,00 por banho",
        price: 100,
      },
      {
        name: "Banho — pacote mensal",
        detail: "Médio • 4 banhos em até 1 mês • R$ 70,00 por banho",
        price: 280,
      },
      {
        name: "Banho — pacote mensal",
        detail: "Grande • 4 banhos em até 1 mês • R$ 90,00 por banho",
        price: 360,
      },
      {
        name: "Banho — pacote quinzenal",
        detail: "Pequeno • 4 banhos em 2 meses • R$ 27,50 por banho",
        price: 110,
      },
      {
        name: "Banho — pacote quinzenal",
        detail: "Médio • 4 banhos em 2 meses • R$ 72,50 por banho",
        price: 290,
      },
      {
        name: "Banho — pacote quinzenal",
        detail: "Grande • 4 banhos em 2 meses • R$ 92,50 por banho",
        price: 370,
      },
      { name: "Tosa na máquina", detail: "Pequeno", price: 70 },
      { name: "Tosa na máquina", detail: "Médio", price: 100 },
      { name: "Tosa na máquina", detail: "Grande", price: 120 },
      { name: "Tosa na máquina", detail: "Gatos", price: 80 },
      { name: "Tosa na tesoura", detail: "Pequeno", price: 80 },
      { name: "Tosa na tesoura", detail: "Médio", price: 110 },
      { name: "Tosa na tesoura", detail: "Grande", price: 140 },
      { name: "Corte de unhas", detail: "Todos os portes", price: 10 },
      { name: "Tosa de patinha", detail: "Todos os portes", price: 20 },
      { name: "Tosa higiênica", detail: "Todos os portes", price: 10 },
      { name: "Hidratação simples", detail: "Todos os portes", price: 20 },
      { name: "Hidratação + desembolar", detail: "Todos os portes", price: 30 },
      { name: "Transporte avulso", detail: "Todos os portes", price: 8 },
      { name: "Transporte mensalista", detail: "Todos os portes", price: 5 },
    ],
  },
];

export const premiumSizeOptions = [
  {
    id: "small",
    label: "Pequeno",
    hint: "até 10 kg",
    image: "pet-size-small.png",
    monthly: 217,
    annual: 2343,
  },
  {
    id: "medium",
    label: "Médio",
    hint: "de 10,1 a 25 kg",
    image: "pet-size-medium.png",
    monthly: 369,
    annual: 3985,
  },
  {
    id: "large",
    label: "Grande",
    hint: "acima de 25 kg",
    image: "pet-size-large.png",
    monthly: 465,
    annual: 5022,
  },
];
