export const SEO_BASE_URL = "https://hospitalcuidary.vercel.app";

const local = "Entre Rios de Minas, MG";
const commonFaq = [
  ["A Cuidary atende 24 horas?", "Sim. O hospital informa atendimento veterinário 24 horas para urgências, emergências e suporte aos pacientes."],
  ["Onde fica a Cuidary?", "A Cuidary fica na Rua Nossa Senhora das Brotas, 179, em Entre Rios de Minas, Minas Gerais."],
  ["Preciso agendar?", "Para urgências e emergências, procure atendimento imediatamente. Para serviços eletivos, confirme disponibilidade e agendamento pelo WhatsApp."],
];

export const seoPages = [
  {
    slug: "hospital-veterinario-24-horas-entre-rios-de-minas",
    title: "Hospital Veterinário 24 Horas em Entre Rios de Minas | Cuidary",
    description: "Hospital veterinário 24 horas em Entre Rios de Minas com consultas, urgência, emergência, exames, cirurgia e internação.",
    h1: "Hospital veterinário 24 horas em Entre Rios de Minas",
    lead: "Atendimento veterinário contínuo para cães e gatos, com estrutura hospitalar para rotina, urgências e emergências.",
    sections: [["Atendimento quando seu pet precisa", "A Cuidary reúne atendimento veterinário 24 horas, consultas, exames, cirurgia e internação em um só local em Entre Rios de Minas."], ["Estrutura hospitalar local", "Ter suporte hospitalar na cidade reduz deslocamentos em momentos críticos e facilita o acompanhamento do paciente durante o tratamento."]],
    faq: commonFaq,
  },
  {
    slug: "urgencia-emergencia-veterinaria-entre-rios-de-minas",
    title: "Urgência e Emergência Veterinária em Entre Rios de Minas | Cuidary",
    description: "Atendimento de urgência e emergência veterinária 24h em Entre Rios de Minas para cães e gatos.",
    h1: "Urgência e emergência veterinária em Entre Rios de Minas",
    lead: "Quando há risco à saúde do pet, rapidez e estrutura fazem diferença. A Cuidary mantém atendimento veterinário 24 horas.",
    sections: [["Quando procurar atendimento", "Dificuldade para respirar, convulsões, sangramento intenso, trauma, intoxicação, dor intensa, perda de consciência e piora súbita exigem avaliação veterinária rápida."], ["O que levar", "Se possível, leve documentos do pet, histórico de medicamentos e informações sobre o que aconteceu. Em suspeita de intoxicação, leve a embalagem do produto envolvido."]],
    faq: commonFaq,
  },
  {
    slug: "consulta-veterinaria-entre-rios-de-minas",
    title: "Consulta Veterinária em Entre Rios de Minas | Cuidary",
    description: "Consulta veterinária para cães e gatos em Entre Rios de Minas, com suporte de exames e estrutura hospitalar.",
    h1: "Consulta veterinária em Entre Rios de Minas",
    lead: "Consultas de rotina e avaliação de sintomas com suporte de exames, internação e cirurgia quando houver indicação clínica.",
    sections: [["Consulta de rotina", "A avaliação periódica ajuda a acompanhar peso, vacinação, prevenção, alimentação, comportamento e mudanças na saúde do animal."], ["Quando há sintomas", "Vômitos persistentes, diarreia, falta de apetite, dor, coceira intensa, alterações urinárias ou comportamento incomum merecem avaliação veterinária."]],
    faq: commonFaq,
  },
  {
    slug: "exames-veterinarios-entre-rios-de-minas",
    title: "Exames Veterinários em Entre Rios de Minas | Cuidary",
    description: "Exames veterinários em Entre Rios de Minas com suporte diagnóstico para cães e gatos.",
    h1: "Exames veterinários em Entre Rios de Minas",
    lead: "Diagnóstico mais rápido começa com avaliação clínica e exames indicados para cada caso.",
    sections: [["Exames com indicação veterinária", "A necessidade de exames depende dos sintomas, histórico, idade e avaliação do médico-veterinário."], ["Tudo conectado ao atendimento", "Ter exames integrados à estrutura hospitalar facilita decisões clínicas e reduz etapas durante o atendimento."]],
    faq: commonFaq,
  },
  {
    slug: "raio-x-veterinario-entre-rios-de-minas",
    title: "Raio X Veterinário em Entre Rios de Minas | Cuidary",
    description: "Raio X veterinário em Entre Rios de Minas para apoio ao diagnóstico de cães e gatos.",
    h1: "Raio X veterinário em Entre Rios de Minas",
    lead: "Exame de imagem para auxiliar a investigação de traumas, alterações ósseas e outras condições conforme indicação veterinária.",
    sections: [["Quando o raio X pode ser indicado", "O exame pode ser solicitado em casos de trauma, suspeita de fratura, alterações ortopédicas e outras situações avaliadas pelo veterinário."], ["Resultado dentro do contexto clínico", "A imagem é interpretada em conjunto com exame físico, histórico e, quando necessário, outros exames."]],
    faq: commonFaq,
  },
  {
    slug: "internacao-veterinaria-entre-rios-de-minas",
    title: "Internação Veterinária em Entre Rios de Minas | Cuidary",
    description: "Internação veterinária em Entre Rios de Minas para cães e gatos que precisam de observação e tratamento hospitalar.",
    h1: "Internação veterinária em Entre Rios de Minas",
    lead: "Suporte hospitalar para pacientes que precisam de monitoramento, medicação e acompanhamento veterinário.",
    sections: [["Quando a internação pode ser necessária", "A decisão depende da condição clínica. Casos com desidratação, dor importante, pós-operatório ou necessidade de monitoramento podem exigir internação."], ["Ambientes separados", "A estrutura da Cuidary prevê áreas de internação para cães, gatos e isolamento, ajudando a organizar o cuidado conforme a necessidade do paciente."]],
    faq: commonFaq,
  },
  {
    slug: "cirurgia-veterinaria-entre-rios-de-minas",
    title: "Cirurgia Veterinária em Entre Rios de Minas | Cuidary",
    description: "Cirurgia veterinária em Entre Rios de Minas com bloco cirúrgico e suporte hospitalar.",
    h1: "Cirurgia veterinária em Entre Rios de Minas",
    lead: "Estrutura para procedimentos cirúrgicos com avaliação veterinária, preparo do paciente e suporte de internação.",
    sections: [["Avaliação antes da cirurgia", "Exames e preparo pré-operatório são definidos conforme o procedimento e as condições do animal."], ["Pós-operatório", "O acompanhamento após o procedimento é parte importante da recuperação e pode incluir medicação, retorno e cuidados específicos em casa."]],
    faq: commonFaq,
  },
  {
    slug: "castracao-cachorro-entre-rios-de-minas",
    title: "Castração de Cachorro em Entre Rios de Minas | Cuidary",
    description: "Castração de cães em Entre Rios de Minas com avaliação veterinária e estrutura hospitalar.",
    h1: "Castração de cachorro em Entre Rios de Minas",
    lead: "A castração é um procedimento cirúrgico e deve ser planejada após avaliação veterinária individual.",
    sections: [["Antes da castração", "A equipe orienta avaliação clínica, jejum e exames quando indicados. Idade, peso e condição de saúde influenciam o planejamento."], ["Depois da cirurgia", "Repouso, proteção da ferida, medicação prescrita e retorno são importantes para uma recuperação adequada."]],
    faq: commonFaq,
  },
  {
    slug: "castracao-gato-entre-rios-de-minas",
    title: "Castração de Gato em Entre Rios de Minas | Cuidary",
    description: "Castração de gatos em Entre Rios de Minas com avaliação veterinária e suporte hospitalar.",
    h1: "Castração de gato em Entre Rios de Minas",
    lead: "Procedimento realizado com planejamento veterinário, orientação pré-operatória e acompanhamento após a cirurgia.",
    sections: [["Avaliação individual", "O momento adequado para castração deve ser definido pelo veterinário considerando idade, peso, histórico e estado de saúde do gato."], ["Cuidados em casa", "Ambiente tranquilo, restrição de esforço e observação da ferida ajudam na recuperação. Siga as orientações prescritas pela equipe."]],
    faq: commonFaq,
  },
  {
    slug: "banho-e-tosa-entre-rios-de-minas",
    title: "Banho e Tosa em Entre Rios de Minas | Cuidary",
    description: "Banho e tosa em Entre Rios de Minas com cuidados de higiene e bem-estar para pets.",
    h1: "Banho e tosa em Entre Rios de Minas",
    lead: "Cuidados de higiene e estética dentro da estrutura Cuidary, com opções de banho e serviços complementares.",
    sections: [["Higiene também é cuidado", "Banho, corte de unhas e cuidados de pelagem contribuem para conforto e permitem observar pele, pelos e regiões que merecem atenção."], ["Serviços conforme o pet", "A indicação de tosa e cuidados adicionais depende do tipo de pelagem, condição da pele e rotina do animal."]],
    faq: commonFaq,
  },
  {
    slug: "veterinario-perto-de-mim-entre-rios-de-minas",
    title: "Veterinário Perto de Mim em Entre Rios de Minas | Cuidary",
    description: "Procurando veterinário perto de você em Entre Rios de Minas? A Cuidary oferece atendimento veterinário 24 horas.",
    h1: "Veterinário perto de mim em Entre Rios de Minas",
    lead: "A Cuidary está na Rua Nossa Senhora das Brotas, 179, com atendimento veterinário 24 horas.",
    sections: [["Localização", "O hospital fica em Entre Rios de Minas e atende tutores que precisam de consulta, urgência, exames, cirurgia, internação e cuidados para seus pets."], ["Antes de sair de casa", "Em casos não emergenciais, você pode falar com a equipe pelo WhatsApp. Em uma emergência, procure atendimento sem esperar resposta online."]],
    faq: commonFaq,
  },
  {
    slug: "emergencia-veterinaria-quando-procurar",
    title: "Emergência Veterinária: Quando Procurar Atendimento | Cuidary",
    description: "Veja sinais que podem exigir atendimento veterinário imediato e onde buscar suporte 24h em Entre Rios de Minas.",
    h1: "Quando uma emergência veterinária precisa de atendimento imediato?",
    lead: "Alguns sinais não devem esperar. Dificuldade respiratória, convulsão, trauma grave, intoxicação e sangramento intenso precisam de avaliação rápida.",
    sections: [["Sinais de alerta", "Colapso, dificuldade para respirar, convulsões repetidas, sangramento importante, trauma, ingestão de substâncias tóxicas e dor intensa são exemplos de situações urgentes."], ["Não tente substituir avaliação profissional", "Informações online ajudam na orientação inicial, mas não substituem exame veterinário. Se o animal estiver piorando, procure atendimento."]],
    faq: commonFaq,
  },
  {
    slug: "clinica-ou-hospital-veterinario",
    title: "Clínica ou Hospital Veterinário: Qual a Diferença? | Cuidary",
    description: "Entenda a diferença entre clínica e hospital veterinário e quando uma estrutura hospitalar pode ser necessária.",
    h1: "Qual a diferença entre clínica e hospital veterinário?",
    lead: "A principal diferença está na estrutura disponível e na capacidade de manter suporte contínuo a pacientes que precisam de exames, cirurgia ou internação.",
    sections: [["Clínica veterinária", "Clínicas costumam concentrar consultas e procedimentos ambulatoriais, podendo oferecer exames e outros serviços conforme a estrutura."], ["Hospital veterinário", "Um hospital pode reunir atendimento contínuo, internação, bloco cirúrgico e suporte diagnóstico, permitindo acompanhar casos de maior complexidade."]],
    faq: commonFaq,
  },
  {
    slug: "plano-veterinario-vale-a-pena",
    title: "Plano Veterinário Vale a Pena? Entenda o Pet Club | Cuidary",
    description: "Entenda quando um plano de benefícios veterinários pode fazer sentido e conheça o Pet Club Cuidary.",
    h1: "Plano veterinário vale a pena?",
    lead: "O valor depende da rotina do pet e de como os benefícios são usados. O Pet Club combina serviços inclusos e descontos em procedimentos.",
    sections: [["Olhe além da mensalidade", "Compare consultas, vacinas, urgência, descontos, carências e serviços de estética. Um plano só faz sentido quando os benefícios combinam com a rotina do animal."], ["Leia a cobertura", "Na Cuidary, as páginas dos planos mostram o que está incluso, os percentuais de desconto e as carências antes da contratação."]],
    faq: [["O Pet Club é seguro de saúde?", "Não. O Pet Club é apresentado como programa de benefícios da Cuidary, com serviços inclusos e descontos conforme o plano."], ...commonFaq],
  },
  {
    slug: "quanto-custa-consulta-veterinaria-entre-rios-de-minas",
    title: "Quanto Custa Consulta Veterinária em Entre Rios de Minas? | Cuidary",
    description: "Saiba o que influencia o valor de uma consulta veterinária e como confirmar o preço atual na Cuidary.",
    h1: "Quanto custa uma consulta veterinária em Entre Rios de Minas?",
    lead: "O valor pode variar conforme tipo de atendimento, horário e necessidade clínica. Confirme o preço atual diretamente com a equipe antes da consulta.",
    sections: [["O que pode alterar o valor", "Consultas de rotina, plantão e atendimentos de urgência podem ter condições diferentes. Exames e procedimentos adicionais são cobrados conforme indicação."], ["Como confirmar", "Use o WhatsApp oficial da Cuidary para consultar valores atuais e disponibilidade. Em uma emergência, priorize o atendimento do pet."]],
    faq: commonFaq,
  },
  {
    slug: "vacinas-para-caes-entre-rios-de-minas",
    title: "Vacinas para Cães em Entre Rios de Minas | Cuidary",
    description: "Vacinação de cães em Entre Rios de Minas com avaliação veterinária e orientação de protocolo.",
    h1: "Vacinas para cães em Entre Rios de Minas",
    lead: "O protocolo de vacinação deve considerar idade, histórico, saúde e risco de exposição do animal.",
    sections: [["Protocolo individual", "Não existe um calendário único para todos os cães. O veterinário avalia histórico vacinal e condições de saúde antes da aplicação."], ["Registro e acompanhamento", "Mantenha a carteira de vacinação atualizada e leve registros anteriores para a consulta."]],
    faq: commonFaq,
  },
  {
    slug: "vacinas-para-gatos-entre-rios-de-minas",
    title: "Vacinas para Gatos em Entre Rios de Minas | Cuidary",
    description: "Vacinação felina em Entre Rios de Minas com orientação veterinária para gatos.",
    h1: "Vacinas para gatos em Entre Rios de Minas",
    lead: "Vacinação felina deve ser planejada de acordo com idade, histórico, estilo de vida e avaliação veterinária.",
    sections: [["Gatos também precisam de prevenção", "Mesmo gatos que vivem dentro de casa precisam de avaliação do protocolo vacinal conforme risco individual."], ["Antes de vacinar", "Informe histórico de doenças, medicamentos e vacinas anteriores. A aplicação deve ocorrer após avaliação do estado de saúde."]],
    faq: commonFaq,
  },
  {
    slug: "meu-cachorro-esta-vomitando-quando-ir-ao-veterinario",
    title: "Cachorro Vomitando: Quando Ir ao Veterinário? | Cuidary",
    description: "Entenda sinais de alerta em casos de vômito em cães e quando procurar atendimento veterinário.",
    h1: "Meu cachorro está vomitando. Quando devo procurar um veterinário?",
    lead: "Um episódio isolado pode ter várias causas, mas vômitos repetidos ou acompanhados de outros sinais precisam de avaliação.",
    sections: [["Procure ajuda rapidamente se", "Houver sangue, fraqueza intensa, dor, barriga distendida, dificuldade para respirar, suspeita de intoxicação, ingestão de objeto ou vômitos persistentes."], ["Evite medicar por conta própria", "Medicamentos humanos podem ser perigosos para animais. Não ofereça remédios sem orientação veterinária."]],
    faq: commonFaq,
  },
  {
    slug: "gato-sem-comer-quando-procurar-veterinario",
    title: "Gato Sem Comer: Quando Procurar Veterinário? | Cuidary",
    description: "Gato sem comer pode precisar de avaliação veterinária. Veja sinais de alerta e quando procurar atendimento.",
    h1: "Meu gato parou de comer. Quando devo procurar um veterinário?",
    lead: "Perda de apetite em gatos merece atenção, especialmente quando persiste ou vem acompanhada de prostração, vômitos, dor ou alterações urinárias.",
    sections: [["Observe outros sinais", "Mudanças no consumo de água, vômitos, diarreia, dificuldade para urinar, dor, esconder-se mais que o normal e apatia ajudam a equipe a avaliar o caso."], ["Não espere piorar", "Gatos podem esconder sinais de doença. Se houver piora, sintomas importantes ou recusa persistente de alimento, procure avaliação veterinária."]],
    faq: commonFaq,
  },
];

export const planSeo = {
  basic: { name: "Plano Basic", title: "Plano Basic Pet Club | Cuidary", description: "Conheça a cobertura do Plano Basic Pet Club Cuidary e veja serviços inclusos, descontos e carências.", planName: "Basic" },
  premium: { name: "Plano Premium", title: "Plano Premium para Cães | Pet Club Cuidary", description: "Plano Premium para cães com consultas, urgência, vacinas, castração e benefícios de estética conforme o porte.", planName: "Premium" },
  essencial: { name: "Plano Essencial", title: "Plano Essencial Pet Club | Cuidary", description: "Confira os benefícios e descontos do Plano Essencial Pet Club Cuidary para cães.", planName: "Essencial" },
  "cat-premium": { name: "Cat Premium", title: "Cat Premium: Plano Exclusivo para Gatos | Cuidary", description: "Plano exclusivo para gatos com consultas, urgência, vacinas felinas, banho e corte de unhas.", planName: "Cat Premium" },
};

export const teamPages = [
  { slug: "equipe/dra-magna-colares", title: "Dra. Magna Colares | Equipe Cuidary", description: "Conheça a Dra. Magna Colares, médica-veterinária da equipe Cuidary em Entre Rios de Minas.", name: "Dra. Magna Colares", role: "Médica-veterinária", credential: "CRMV 23577" },
  { slug: "equipe/dr-lucas-fiusa", title: "Dr. Lucas Fiusa | Equipe Cuidary", description: "Conheça o Dr. Lucas Fiusa, médico-veterinário da equipe Cuidary em Entre Rios de Minas.", name: "Dr. Lucas Fiusa", role: "Médico-veterinário", credential: "CRMV 28445043" },
  { slug: "equipe/isadora-resende", title: "Isadora Resende | Equipe Cuidary", description: "Conheça Isadora Resende, gerente administrativa da Cuidary em Entre Rios de Minas.", name: "Isadora Resende", role: "Gerente Administrativa", credential: "" },
];

export const allSeoRoutes = [
  ...seoPages.map((page) => ({ path: `/${page.slug}`, ...page })),
  ...Object.entries(planSeo).map(([slug, page]) => ({ path: `/planos/${slug}`, ...page })),
  ...teamPages.map((page) => ({ path: `/${page.slug}`, ...page })),
];
